### ISSUE TITLE
32 bit version of wineasio not compiling, even with latest version of wine-staging (10.12)

### ISSUE THREAD

**Issue by 5unekku** [wineasio/wineasio#120]
i'm using cachyos (arch linux) and have installed wine-staging through the cachyos repos. this worked with neither 10.10 or 10.12 from the cachyos-v3 and cachyos-extra-v3 repos respectively. compilation of the 64 bit version was very easy, and worked instantly.

i installed the 64 bit version with the wineasio package on the arch user repository, but the wineasio32 package had compilation errors (seen below). manually downloading the package from the github releases page resulted in identical errors. it seems to be missing 32 bit libraries, despite the respective libraries being present, as far as i can tell.

log of `make 32` (automatically performed by yay (aur helper):
```
❯ yay -S wineasio32
AUR Explicit (1): wineasio32-1.3.0-2
:: PKGBUILD up to date, skipping download: wineasio32
==> Making package: wineasio32 1.3.0-2 (Fri 01 Aug 2025 06:51:02 PM)
==> Retrieving sources...
  -> Downloading wineasio-1.3.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  100k  100  100k    0     0   221k      0 --:--:-- --:--:-- --:--:--  221k
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    wineasio-1.3.0.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: wineasio32
==> Making package: wineasio32 1.3.0-2 (Fri 01 Aug 2025 06:51:02 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found wineasio-1.3.0.tar.gz
==> Validating source files with sha256sums...
    wineasio-1.3.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting wineasio-1.3.0.tar.gz with bsdtar
==> Sources are ready.
==> Making package: wineasio32 1.3.0-2 (Fri 01 Aug 2025 06:51:03 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make build ARCH=i386 M=32
make[1]: Entering directory '/home/jimmy/.cache/yay/wineasio32/src/wineasio-1.3.0'
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows -march=native -O3 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/asio.c.o asio.c
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows -march=native -O3 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/jackbridge.c.o jackbridge.c
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows -march=native -O3 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/main.c.o main.c
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows -march=native -O3 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/regsvr.c.o regsvr.c
winebuild -m32 --dll --fake-module -E wineasio.dll.spec build32/asio.c.o build32/jackbridge.c.o build32/main.c.o build32/regsvr.c.o -o build32/wineasio32.dll
winegcc build32/asio.c.o build32/jackbridge.c.o build32/main.c.o build32/regsvr.c.o -shared -m32 wineasio.dll.spec -L/usr/lib32/wine -L/usr/lib/wine -L/usr/lib/i386-linux-gnu/wine -L/usr/lib/i386-linux-gnu/wine-development -L/opt/wine-stable/lib -L/opt/wine-stable/lib/wine -L/opt/wine-stable/lib32 -L/opt/wine-stable/lib32/wine -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine -L/opt/wine-staging/lib32 -L/opt/wine-staging/lib32/wine \
	-lodbc32 -lole32 -luuid -lwinmm -o build32/wineasio32.dll.so
/usr/bin/ld: cannot find -lodbc32: No such file or directory
/usr/bin/ld: cannot find -lole32: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/libuuid.so when searching for -luuid
/usr/bin/ld: cannot find -lwinmm: No such file or directory
/usr/bin/ld: cannot find -ladvapi32: No such file or directory
/usr/bin/ld: cannot find -luser32: No such file or directory
/usr/bin/ld: cannot find -lwinecrt0: No such file or directory
/usr/bin/ld: cannot find -lkernel32: No such file or directory
/usr/bin/ld: cannot find -lntdll: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed
make[1]: *** [Makefile.mk:103: build32/wineasio32.dll.so] Error 2
make[1]: Leaving directory '/home/jimmy/.cache/yay/wineasio32/src/wineasio-1.3.0'
make: *** [Makefile:17: 32] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: wineasio32-exit status 4
removing untracked AUR files from cache...
:: Cleaning (1/1): /home/jimmy/.cache/yay/wineasio32
Removing wineasio-1.3.0.tar.gz
 -> Failed to install the following packages. Manual intervention is required:
wineasio32 - exit status 4
```

manual `make 32`:
```
❯ make 32
make build ARCH=i386 M=32
make[1]: Entering directory '/home/jimmy/Downloads/wineasio-1.3.0'
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/asio.c.o asio.c
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/jackbridge.c.o jackbridge.c
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/main.c.o main.c
gcc -c -I. -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -O2 -DNDEBUG -fvisibility=hidden -o build32/regsvr.c.o regsvr.c
winebuild -m32 --dll --fake-module -E wineasio.dll.spec build32/asio.c.o build32/jackbridge.c.o build32/main.c.o build32/regsvr.c.o -o build32/wineasio32.dll
winegcc build32/asio.c.o build32/jackbridge.c.o build32/main.c.o build32/regsvr.c.o -shared -m32 wineasio.dll.spec -L/usr/lib32/wine -L/usr/lib/wine -L/usr/lib/i386-linux-gnu/wine -L/usr/lib/i386-linux-gnu/wine-development -L/opt/wine-stable/lib -L/opt/wine-stable/lib/wine -L/opt/wine-stable/lib32 -L/opt/wine-stable/lib32/wine -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine -L/opt/wine-staging/lib32 -L/opt/wine-staging/lib32/wine \
        -lodbc32 -lole32 -luuid -lwinmm -o build32/wineasio32.dll.so
/usr/bin/ld: cannot find -lodbc32: No such file or directory
/usr/bin/ld: cannot find -lole32: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/libuuid.so when searching for -luuid
/usr/bin/ld: cannot find -lwinmm: No such file or directory
/usr/bin/ld: cannot find -ladvapi32: No such file or directory
/usr/bin/ld: cannot find -luser32: No such file or directory
/usr/bin/ld: cannot find -lwinecrt0: No such file or directory
/usr/bin/ld: cannot find -lkernel32: No such file or directory
/usr/bin/ld: cannot find -lntdll: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed
make[1]: *** [Makefile.mk:103: build32/wineasio32.dll.so] Error 2
make[1]: Leaving directory '/home/jimmy/Downloads/wineasio-1.3.0'
make: *** [Makefile:17: 32] Error 2
```

**Comment by falkTX** [comment]
seems like your wine version no longer has 32bit libs? or they are in a location not included in the many within the makefile

**Comment by 5unekku** [comment]
> seems like your wine version no longer has 32bit libs? or they are in a location not included in the many within the makefile

that's what it seems like, but no matter how much i scavenge my repos (arch and cachyos) there's almost nothing mentioning wine-devel, lib32-wine, wine-multilib, nothing. not even in the aur. i've been at this all day. my libs seem to be in `/usr/lib/wine`, including `x86_64-unix` and `x86_64-windows`, and `i386-windows`. the dlls seem to be in the windows folders, and yet i continue to have these files.

**Comment by falkTX** [comment]
where are the i386-unix files?

**Comment by 5unekku** [comment]
there isn't any it seems. not in `/usr/lib/wine` and no wine in `/usr/lib32`

**Comment by dekrain** [comment]
This is likely due to the new WoW64 build enabled on arch, which uses only 64-bit native libraries and internally handles the 32-bit to 64-bit wine calls for apps. I don't know would it need to be done to make it work with external projects like wineasio (and my fork that uses pipewire), but at least 64-bit versions would be supported (32-bit apps still require 32-bit ABI, so it couldn't just use the 64-bit ones).

**Comment by ivohulsman** [comment]
I have gotten this to compile on CachyOS after installing `wine32` from the AUR. Note that it conflicts with wine/wine-staging so after this I had to switch back to either one.

**Comment by ididrummer** [comment]
what worked for me was to roll back to wine 9.9 or so, install wineasio normally, and then update wine back to to current
