### ISSUE TITLE
Fatal error.

### ISSUE THREAD

**Issue by ghost** [wineasio/wineasio#22]
After typing make 64 I get an fatal error.
What am I doing wrong?

make build ARCH=x86_64 M=64
make[1]: Entering directory '/home/usr/wineasio'
gcc -c -I. -Irtaudio/include -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows    -m64 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration  -DNATIVE_INT64 -O2 -DNDEBUG -fvisibility=hidden -o build64/asio.c.o asio.c
asio.c:44:10: fatal error: objbase.h: No such file or directory
   44 | #include "objbase.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.mk:98: build64/asio.c.o] Error 1
make[1]: Leaving directory '/home/usr/wineasio'
make: *** [Makefile:18: 64] Error 2
usr@pop-os:~/wineasio$ make 64
make build ARCH=x86_64 M=64
make[1]: Entering directory '/home/usr/wineasio'
gcc -c -I. -Irtaudio/include -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows    -m64 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration  -DNATIVE_INT64 -O2 -DNDEBUG -fvisibility=hidden -o build64/asio.c.o asio.c
asio.c:44:10: fatal error: objbase.h: No such file or directory
   44 | #include "objbase.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.mk:98: build64/asio.c.o] Error 1
make[1]: Leaving directory '/home/usr/wineasio'
make: *** [Makefile:18: 64] Error 2

**Comment by falkTX** [comment]
You are missing wine development header/packages.

**Comment by ghost** [comment]
After installing the latest wine devel version (6.1) it didn't work but it worked with 5.5-5 (devel). Thank you for your help.
