### ISSUE TITLE
Unable to build on Kubuntu 22.04 LTS

### ISSUE THREAD

**Issue by 2004seraph** [wineasio/wineasio#69]
Attempting to run `make 64` or `make 32` nets the same error message about the jack audio audio library.

```
seraph@cccyantop:~/Downloads/wineasio-1.1.0$ make 64

make build ARCH=x86_64 M=64

make[1]: Entering directory '/home/seraph/Downloads/wineasio-1.1.0'

gcc -c -I. -Irtaudio/include -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m64 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -I@includedir@ -DNATIVE_INT64 -O2 -DNDEBUG -fvisibility=hidden -o build64/asio.c.o asio.c

asio.c:33:10: fatal error: jack/jack.h: No such file or directory
   33 | #include <jack/jack.h>
      |          ^~~~~~~~~~~~~

compilation terminated.

make[1]: *** [Makefile.mk:102: build64/asio.c.o] Error 1

make[1]: Leaving directory '/home/seraph/Downloads/wineasio-1.1.0'

make: *** [Makefile:18: 64] Error 2
```

Running `find /usr -name jack.h` gives the following output:

```
/usr/src/linux-headers-6.4.6-76060406/include/sound/jack.h
/usr/src/linux-headers-6.2.6-76060206/include/sound/jack.h
```

I have tried installing `jack-tools` through apt-get to no avail. I have tried cloning the jack1 repo and adding it to the PKG_CONFIG_PATH variable, this didn't change anything.

**Comment by 2004seraph** [comment]
Managed to progress past this error by running `sudo apt install libjack-jackd2-dev` but now the build fails because of `objbase.h`.

```
seraph@cccyantop:~/Downloads/wineasio-1.1.0$ make 64
make build ARCH=x86_64 M=64
make[1]: Entering directory '/home/seraph/Downloads/wineasio-1.1.0'
gcc -c -I. -Irtaudio/include -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m64 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration -I@includedir@ -DNATIVE_INT64 -O2 -DNDEBUG -fvisibility=hidden -o build64/asio.c.o asio.c
asio.c:44:10: fatal error: objbase.h: No such file or directory
   44 | #include "objbase.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.mk:102: build64/asio.c.o] Error 1
make[1]: Leaving directory '/home/seraph/Downloads/wineasio-1.1.0'
make: *** [Makefile:18: 64] Error 2

```

Running `find objbase.h` turns up nothing, installing `libwine-dev` does not change anything.

**Comment by 2004seraph** [comment]
Trying to build the 32 bit version gives me this error:

```
seraph@cccyantop:~/Downloads/wineasio-1.1.0$ make 32

make build ARCH=i386 M=32
make[1]: Entering directory '/home/seraph/Downloads/wineasio-1.1.0'
gcc -c -I. -Irtaudio/include -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration  -O2 -DNDEBUG -fvisibility=hidden -o build32/asio.c.o asio.c

In file included from asio.c:27:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.mk:102: build32/asio.c.o] Error 1
make[1]: Leaving directory '/home/seraph/Downloads/wineasio-1.1.0'
make: *** [Makefile:15: 32] Error 2
```

**Comment by mickski56** [comment]
objbase.h is part of wine check INCLUDE_PATH in Makefile.mk points to where wine is installed.

bits/libc-header-start.h is part of glibc. Do you have a 32bit or multilib dev environment set up ?

**Comment by williamcorney** [comment]
In my experience you have to build wine from source  and then install that wine you have built and use that to build the wineasio files.

The reason is because its only by building it from source that you get the necessary header files in the location its look for them.  My experience is more with OSX but I recall that just using the 'dev' 'staging' versions didn't do the trick.  It was when I built wine from source that I started making progress.

**Comment by Dehir** [comment]
Sorry for posting but think this issue could be closed now

Some distro like debian based have placed objbase.h in different path that is lacking @ Makefile.mk

example in ubuntu the file is located at /usr/include/wine/wine/windows but Makefile.mk does have only include/wine/windows. Adding line 

> INCLUDE_PATH         += -I$(PREFIX)/include/wine/wine/windows

at proper place in Makefile.mk fixed the issue
